package forca;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JDialog;


public class principal extends javax.swing.JFrame { //criacao de variáveis e definição das imagens e cria os vetores
    String PalavraSorteada = new String();
    ArrayList Tentativas = new ArrayList();
    int MaxTentativas = 6 ;
    int NumTentativas = 0 ;
    boolean FimDoJogo = true;
    ImageIcon icon0 = new ImageIcon("forca00.jpg");
    ImageIcon icon1 = new ImageIcon("forca11.jpg");
    ImageIcon icon2 = new ImageIcon("forca22.jpg");
    ImageIcon icon3 = new ImageIcon("forca33.jpg");
    ImageIcon icon4 = new ImageIcon("forca44.jpg");
    ImageIcon icon5 = new ImageIcon("forca55.jpg");
    ImageIcon icon6 = new ImageIcon("forca66.jpg");
    ArrayList PalavrasArquivo = new ArrayList();
    ArrayList DicasArquivo = new ArrayList();


    @Override
    public Image createImage(int width, int height) {
        return super.createImage(width, height);
    }

    /** Creates new form principal */
    public principal() {
        
        initComponents();

        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        joga_nov = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jogo_novo = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        deseja_sair = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        btsim = new javax.swing.JButton();
        btnao = new javax.swing.JButton();
        PalavraForca = new javax.swing.JTextField();
        CampoTentar = new javax.swing.JTextField();
        lblDigite = new javax.swing.JLabel();
        btVerifica = new javax.swing.JButton();
        LabelImagem = new javax.swing.JLabel();
        TxtDica = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel1.setText("Você ganhou. Quer jogar novamente?");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forca/salvar.jpg"))); // NOI18N
        jButton1.setText("Sim");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forca/cancelar.jpg"))); // NOI18N
        jButton2.setText("Não");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout joga_novLayout = new javax.swing.GroupLayout(joga_nov.getContentPane());
        joga_nov.getContentPane().setLayout(joga_novLayout);
        joga_novLayout.setHorizontalGroup(
            joga_novLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joga_novLayout.createSequentialGroup()
                .addGroup(joga_novLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, joga_novLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, joga_novLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        joga_novLayout.setVerticalGroup(
            joga_novLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joga_novLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(joga_novLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel3.setText("Você perdeu. Jogar novamente?");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forca/salvar.jpg"))); // NOI18N
        jButton3.setText("Sim");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forca/cancelar.jpg"))); // NOI18N
        jButton4.setText("Não");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jogo_novoLayout = new javax.swing.GroupLayout(jogo_novo.getContentPane());
        jogo_novo.getContentPane().setLayout(jogo_novoLayout);
        jogo_novoLayout.setHorizontalGroup(
            jogo_novoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jogo_novoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jogo_novoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jogo_novoLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(61, 61, 61)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jogo_novoLayout.setVerticalGroup(
            jogo_novoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jogo_novoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jogo_novoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        deseja_sair.setBounds(new java.awt.Rectangle(50, 50, 240, 200));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jLabel4.setText("Deseja mesmo sair?");

        btsim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forca/salvar.jpg"))); // NOI18N
        btsim.setText("Sim");
        btsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimActionPerformed(evt);
            }
        });

        btnao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forca/cancelar.jpg"))); // NOI18N
        btnao.setText("Não");
        btnao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deseja_sairLayout = new javax.swing.GroupLayout(deseja_sair.getContentPane());
        deseja_sair.getContentPane().setLayout(deseja_sairLayout);
        deseja_sairLayout.setHorizontalGroup(
            deseja_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deseja_sairLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btsim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnao)
                .addGap(20, 20, 20))
            .addGroup(deseja_sairLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        deseja_sairLayout.setVerticalGroup(
            deseja_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deseja_sairLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addGroup(deseja_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsim)
                    .addComponent(btnao))
                .addGap(29, 29, 29))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Forca - Enforcado");

        PalavraForca.setEditable(false);
        PalavraForca.setFont(new java.awt.Font("Arial Black", 0, 36));
        PalavraForca.setEnabled(false);

        CampoTentar.setFont(new java.awt.Font("Arial Black", 0, 12));
        CampoTentar.setEnabled(false);

        lblDigite.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
        lblDigite.setText("Digite uma letra:");
        lblDigite.setEnabled(false);

        btVerifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forca/verificar.jpg"))); // NOI18N
        btVerifica.setText("Verificar");
        btVerifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerificaActionPerformed(evt);
            }
        });

        LabelImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forca/forca00.jpg"))); // NOI18N

        TxtDica.setEditable(false);
        TxtDica.setFont(new java.awt.Font("Verdana", 0, 10));
        TxtDica.setEnabled(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forca/enforcado.jpg"))); // NOI18N

        jMenu1.setText("Arquivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forca/novo.jpg"))); // NOI18N
        jMenuItem1.setText("Novo Jogo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forca/sair.jpg"))); // NOI18N
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastrar");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forca/novo_txt.jpg"))); // NOI18N
        jMenuItem3.setText("Palavras e Dicas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelImagem)
                    .addComponent(jLabel2))
                .addGap(199, 199, 199))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PalavraForca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDigite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoTentar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVerifica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDica, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDigite)
                    .addComponent(CampoTentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVerifica)
                    .addComponent(TxtDica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PalavraForca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVerificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerificaActionPerformed
        if(!FimDoJogo){//verifica se não é o fim do jogo
            tentarletra(CampoTentar.getText());//se não for, pega a letra escrita e verifica se tem na palavra
            CampoTentar.setText("");//deixa o campo onde são digitadas as letras vazio
        }

    }//GEN-LAST:event_btVerificaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        lblDigite.enable(true);//habilita os campos do jogo
        CampoTentar.enable(true);
       // btVerifica.enable(true); o botão não desabilitado pois depois não habilitava
        TxtDica.enable(true);
        PalavraForca.enable(true);
        // Dá um reset no jogo:
        PalavraForca.setText("");//limpa os campos
        Tentativas.clear();//limpa as tentativas
        sortearpalavra(); //pega uma palavra do Txt e sorteia
        FimDoJogo=false; //Como ainda não é o fim do jogo, a opção se torna falsa
        LabelImagem.setIcon(icon0); //seta o ícone normal, do desenho da forca
        NumTentativas=0; // zera o numero de tentativas
        desenharpalavra(false);//a palavra só será desenhada se o usuário perder o jogo
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        deseja_sair.setLocationRelativeTo(null);
        deseja_sair.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Cadastro cadastro = new Cadastro();
        cadastro.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Dá um reset no jogo:
        PalavraForca.setText("");
        Tentativas.clear();
        sortearpalavra();
        FimDoJogo=false;
        LabelImagem.setIcon(icon0);
        NumTentativas=0;
        desenharpalavra(false);
        joga_nov.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Dá um reset no jogo:
        PalavraForca.setText("");
        Tentativas.clear();
        sortearpalavra();
        FimDoJogo=false;
        LabelImagem.setIcon(icon0);
        NumTentativas=0;
        desenharpalavra(false);
        jogo_novo.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btsimActionPerformed

    private void btnaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaoActionPerformed
        deseja_sair.setVisible(false);
    }//GEN-LAST:event_btnaoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoTentar;
    private javax.swing.JLabel LabelImagem;
    private javax.swing.JTextField PalavraForca;
    private javax.swing.JTextField TxtDica;
    private javax.swing.JButton btVerifica;
    private javax.swing.JButton btnao;
    private javax.swing.JButton btsim;
    private javax.swing.JDialog deseja_sair;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JDialog joga_nov;
    private javax.swing.JDialog jogo_novo;
    private javax.swing.JLabel lblDigite;
    // End of variables declaration//GEN-END:variables

    @SuppressWarnings("empty-statement")
    public void sortearpalavra() {
        try {
            File Arquivo = new File("Palavras.txt"); //lê o arquivo Txt
            FileReader leitor = new FileReader(Arquivo);
            BufferedReader leitorBuf = new BufferedReader(leitor);
            PalavrasArquivo.clear(); //limpa o temporario que armazena as palavras
            DicasArquivo.clear(); //limpa o temporaio que aramzena a dica

            String linha=null;

            while((linha = leitorBuf.readLine()) !=null){
                String colunas[] = linha.split("#"); //lê a linha contendo a palavra e a dica, sabendo q as mesmas sao separadas pelo
                PalavrasArquivo.add(colunas[0]);//caractere #
                DicasArquivo.add(colunas[1]);
            }

            leitorBuf.close();

            int TotalPalavras = PalavrasArquivo.size();//lê o tamanho da palavra para desenhar os traços
            int CodPalavraSorteada = (int) (Math.random()*(TotalPalavras)) ;//sorteia uma palavra randomicamente
            PalavraSorteada = (String) PalavrasArquivo.get(CodPalavraSorteada);//pega a plavra sorteada
            PalavraSorteada= PalavraSorteada.toUpperCase();//coloca em maiusculo
            TxtDica.setText("DICA: "+(String) DicasArquivo.get(CodPalavraSorteada));//pega a dica e exibe
        }
        catch(Exception ex) {
            System.out.println("Erro: "+ ex.toString());};
    }

    public void desenharpalavra(boolean MostrarTodaAPalavra){
        String tempTexto = new String();
        boolean faltauma = false;
        for(int n=1;n<=PalavraSorteada.length();n++){//pega o tamanho da palavra e cria os tracinhos
            if((MostrarTodaAPalavra) || (Tentativas.contains(PalavraSorteada.substring(n-1, n)))){
                tempTexto=tempTexto+PalavraSorteada.substring(n-1, n);
            }else{
                tempTexto=tempTexto+"_";
                faltauma=true;
            }
            tempTexto=tempTexto+" ";
        }

        PalavraForca.setText(tempTexto);

        if(!faltauma){
            FimDoJogo=true;
                if ((NumTentativas)<6){//verifica se o numero de tentativas é menor que 6; se for, o usuario ganhou
                    joga_nov.pack();//abre a mensagem que pede se o usuário quer jogar novamente
                    joga_nov.setLocationRelativeTo(null);
                    joga_nov.setVisible(true);
                }
            
            // Dá pra mostrar uma outra mensagem aqui.
        }
    }

    public void tentarletra(String Letra){
        Letra= Letra.toUpperCase();
        if(Tentativas.contains(Letra)){
            // Mostrar mensagem de que já foi tentada esta letra
        }else{ 
            // Armazena a letra nova na lista de tentativas.
            Tentativas.add(Letra);
            if(PalavraSorteada.contains(Letra)){
                // Acertou
                desenharpalavra(false);
            }else{
                NumTentativas=NumTentativas+1;//vai adicionando o numero de tentativas; se errar, adiciona o desenho
                switch(NumTentativas){
                    case(1):{
                        LabelImagem.setIcon(icon1);
                        break;
                    }
                    case(2):{
                        LabelImagem.setIcon(icon2);
                        break;
                    }
                    case(3):{
                        LabelImagem.setIcon(icon3);
                        break;
                    }
                    case(4):{
                        LabelImagem.setIcon(icon4);
                        break;
                    }
                    case(5):{
                        LabelImagem.setIcon(icon5);
                        break;
                    }
                    case(6):{
                        LabelImagem.setIcon(icon6);
                        FimDoJogo=true;
                        desenharpalavra(true);
                        FimDoJogo=true;
                        jogo_novo.pack();
                        jogo_novo.setLocationRelativeTo(null);
                        jogo_novo.setVisible(true);
                        break;
                    }
                }
            }
        }
    }
}
